### ISSUE TITLE
Analysis of re-using Gitter bot vs building it from scratch

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/slack-bot#2]
Should we re-use https://github.com/datopian/ourbot or build it from scratch?

## Acceptance criteria

* [x] I have a decision about how should we proceed

## Tasks

* [x] do ~1h analysis of how to build it from scratch, e.g., if we wanted to have similar functionality as in the Gitter
* [x] do <1h analysis of what would it take to re-use Gitter bot, e.g., how good is the code, is it re-usable at all, is it Gitter specific etc.

## Analysis

Our gitter bot is based on hubot and contains functionalities such as writing to google docs, making actions on github (issue/milestone creation/closing) - https://github.com/datopian/ourbot

From our previous experience, the bot on gitter was doing some tasks very well (writing standups and other things into google spreadshet) but failed with tasks related to github (we needed to fix it several times, sometimes it reports that task is succeeded but it didn't etc.).

Overall, it looks like we could re-use some part of the gitter bot, e.g., we could take script for writing into google spreadsheet. However, I don't think it worth to re-use the entire project - sometimes it is easier to create from scratch rather than refactoring an old project.

### Building a bot from scratch and re-using some parts of `ourbot`

There are several frameworks, toolkits and platforms to easily build a bot for Slack or any other messaging app. We've considered some of most popular ones:

* Hubot - https://github.com/hubotio/hubot
  * looks like Slack recommendation as they link to it in their articles
  * framework which extendable and easy-to-use
  * free but we need to host it somewhere, e.g., on Heroku and with free plan it will need to sleep 6h per 24h *which is OK from our previous experience** but now we have a larger team so everyone should know when it sleeps
* Botkit by Howdy.ai - https://github.com/howdyai/botkit
  * easy-to-use
  * extendable
  * toolkit with list of plugins
  * free but need to host
* "Standard Library" - 
  * it offers serverless bots
  * it has a tutorial for building bots
  * it looks simple to build a simple bot
  * it is a freemium service **so not sure if we don't end up with paid option**

From initial research it looks like both Hubot and Botkit can be used to build a bot. **Based on our experience with Hubot (we've deployed and enjoyed it), we prefer choosing it again.**

**Comment by anuveyatsu** [comment]
FIXED, we will build a bot using Hubot from scratch by re-using some parts of `ourbot`.
